export const nestedPascalObject = {
  data: {
    cars: [
      {
        brand: 'Seat',
        models: [
          'Alhambra',
          'Altea',
          'Altea XL',
          'Arosa',
          'Cordoba',
          'Cordoba Vario',
          'Exeo',
          'Ibiza',
          'Ibiza ST',
          'Exeo ST',
          'Leon',
          'Leon ST',
          'Inca',
          'Mii',
          'Toledo',
        ],
      },
      {
        brand: 'Renault',
        models: [
          'Captur',
          'Clio',
          'Clio Grandtour',
          'Espace',
          'Express',
          'Fluence',
          'Grand Espace',
          'Grand Modus',
          'Grand Scenic',
          'Kadjar',
          'Kangoo',
          'Kangoo Express',
          'Koleos',
          'Laguna',
          'Laguna Grandtour',
          'Latitude',
          'Mascott',
          'Mégane',
          'Mégane CC',
          'Mégane Combi',
          'Mégane Grandtour',
          'Mégane Coupé',
          'Mégane Scénic',
          'Scénic',
          'Talisman',
          'Talisman Grandtour',
          'Thalia',
          'Twingo',
          'Wind',
          'Zoé',
        ],
      },
    ],
  },
};

export const convertedPascalCase = {
  Data: {
    Cars: [
      {
        Brand: 'Seat',
        Models: [
          'Alhambra',
          'Altea',
          'Altea XL',
          'Arosa',
          'Cordoba',
          'Cordoba Vario',
          'Exeo',
          'Ibiza',
          'Ibiza ST',
          'Exeo ST',
          'Leon',
          'Leon ST',
          'Inca',
          'Mii',
          'Toledo',
        ],
      },
      {
        Brand: 'Renault',
        Models: [
          'Captur',
          'Clio',
          'Clio Grandtour',
          'Espace',
          'Express',
          'Fluence',
          'Grand Espace',
          'Grand Modus',
          'Grand Scenic',
          'Kadjar',
          'Kangoo',
          'Kangoo Express',
          'Koleos',
          'Laguna',
          'Laguna Grandtour',
          'Latitude',
          'Mascott',
          'Mégane',
          'Mégane CC',
          'Mégane Combi',
          'Mégane Grandtour',
          'Mégane Coupé',
          'Mégane Scénic',
          'Scénic',
          'Talisman',
          'Talisman Grandtour',
          'Thalia',
          'Twingo',
          'Wind',
          'Zoé',
        ],
      },
    ],
  },
};
